server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${dbhost}/test?serverTimezone=Asia/Shanghai&autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF-8
    username: ${dbuser}
    password: ${dbpw}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: creditHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  security:
    user:
      name: kasaya
      password: kasaya
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: springcloud
  customize: 
    globalsecurity: 
      enabled: true
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.oycl.orm.model
  global-config:
    db-column-underline: true
    capital-mode: false
  configuration:
    map-underscore-to-camel-case: true

user:
  mate: zzzzz
# 打开feign对hystrix的支持
feign:
  hystrix:
    enabled: true

#配置ribbon time-out
# interface-service: 在zuun 中这里配service-id
ribbon:
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 0
  ConnectTimeout: 10000 #10秒
  ReadTimeout: 10000 #10秒

management:
  endpoints:
    web:
      exposure:
        include: ['bus-refresh','refresh-gateway']
    enabled-by-default: true
hystrix:
  threadpool:
    default:
      coreSize: 10  #线程池核心线程数
  command: 
    default:
      execution:
        isolation:
          strategy: SEMAPHORE #隔离策略，默认是Thread, 可选Thread｜Semaphore
          thread:
            timeoutInMilliseconds: 1000 #命令执行超时时间 超时时间
            interruptOnTimeout: true #发生超时是是否中断，默认true
        timeout:
          enabled: true #执行是否启用超时，默认启用true
      circuitBreaker:
        requestVolumeThreshold: 3  #当在配置时间窗口内达到此数量后，进行短路。默认20个
        sleepWindowInMilliseconds: 5000  #短路多久以后开始尝试是否恢复，默认5毫秒
        errorThresholdPercentage: 50%  #出错百分比阈值，当达到此阈值后，开始短路。默认50%
---
spring:
  profiles: dev
dbhost: sh-cdb-fhama989.sql.tencentcdb.com:63156
dbuser: root
dbpw: jHnXk31UXZasddf
---
spring:
  profiles: local
dbhost: sh-cdb-fhama989.sql.tencentcdb.com:63156
dbuser: root
dbpw: jHnXk31UXZasddf


