zuul:
  sensitiveHeaders:
  #ignoredHeaders: Cookies,Set-Cookie
  prefix: /kasaya
  routes:
    # 登录主工程
    main-service:
      path: /main/**
      serviceId: main-service
  ratelimit:
    enabled: true
    behind-proxy: true  #代理之后
    default-policy: #可选 - 针对所有的路由配置的策略，除非特别配置了policies
      limit:  5 #每个刷新时间窗口对应的请求数量限制
      refresh-interval: 1 #刷新时间窗口的时间，默认值 (秒)
      type:
        - ORIGIN
        - URL
        - USER

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  #开启okhttp3
  okhttp:
    enabled: true

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: springcloud

management:
  endpoints:
    web:
      exposure:
        include: ['*']


---
spring:
  profiles: dev

---
spring:
  profiles: local

