server:
  servlet:
    context-path: /ser
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${dbhost}/test?serverTimezone=Asia/Shanghai&autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF-8
    username: ${dbuser}
    password: ${dbpw}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: creditHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  security:
    user:
      name: kasaya
      password: kasaya

# 打开feign对hystrix的支持
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL

#配置ribbon time-out
ribbon:
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 0
  ConnectTimeout: 10000 #10秒
  ReadTimeout: 10000 #10秒

management:
  endpoints:
    web:
      exposure:
        include: '*'

# 参数可以参加 HystrixCommandProperties 这个文件
hystrix:
  threadpool:
    default:
      coreSize: 10  #线程池核心线程数
  command:
    MainApi#login(LoginInput): #设置某一个接口 default: 设置全部接口
      execution:
        isolation:
          strategy: SEMAPHORE #隔离策略，默认是Thread, 可选Thread｜Semaphore
          thread:
            timeoutInMilliseconds: 5200 #命令执行超时时间 超时时间
            interruptOnTimeout: true #发生超时是是否中断，默认true
        timeout:
          enabled: true #执行是否启用超时，默认启用true
      circuitBreaker:
        requestVolumeThreshold: 3  #当在配置时间窗口内达到此数量后，进行短路。默认20个
        sleepWindowInMilliseconds: 5000  #短路多久以后开始尝试是否恢复，默认5毫秒
        errorThresholdPercentage: 50%  #出错百分比阈值，当达到此阈值后，开始短路。默认50%
---
spring:
  profiles: dev
dbhost: sh-cdb-fhama989.sql.tencentcdb.com:63156
dbuser: root
dbpw: jHnXk31UXZasddf
---
spring:
  profiles: local
dbhost: sh-cdb-fhama989.sql.tencentcdb.com:63156
dbuser: root
dbpw: jHnXk31UXZasddf
